### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by randoms** [BluewhaleRobot/xq-manual#3]
If you have experience any problem with the doc and want to improve it. Please open pull request to us.

**Comment by Raman1121** [comment]
What are we supposed to do in this?

**Comment by Raman1121** [comment]
I want to be assigned to this issue. I was thinking of re-writing this documentation in English for a more diverse audience.

**Comment by randoms** [comment]
Thank you for your help. We have English documents. And it would be great if you can help to review [it](https://github.com/BluewhaleRobot/xq-manual-en/issues/1).

**Comment by Raman1121** [comment]
Do you want any help in any specific area in your documentation?

**Comment by randoms** [comment]
Yes, any help is welcomed.
